export default {
	USER_LOGIN: 'USER_LOGIN',
	USER_LOGOUT: 'USER_LOGOUT',
	ITEM_ADD: 'ITEM_ADD',
	ITEM_REMOVE: 'ITEM_REMOVE',
	ITEM_MOVE: 'ITEM_MOVE',
	ITEM_CLICK: 'ITEM_CLICK',
    WALL_LOAD: 'WALL_LOAD',
    WALL_SAVE: 'WALL_SAVE',
    WALL_RENAME: 'WALL_RENAME',
    FWINDOW_SHOW: 'FWINDOW_SHOW',
    FWINDOW_HIDE: 'FWINDOW_HIDE',
    FWINDOW_CONTENT: 'FWINDOW_CONTENT',
}
